name: ðŸš€ åŒæ­¥å¤„ç†

on:
  workflow_dispatch:   # æ‰‹åŠ¨è§¦å‘
  workflow_run:       # åœ¨ Build workflow å®ŒæˆåŽè§¦å‘
    workflows: ["ðŸ’» å›ºä»¶ç¼–è¯‘"]   # å¡«ä½  Build workflow çš„åå­—
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync OTA
        run: |
          mkdir -p ota
          wget -q https://github.com/zhiern/ZeroWrt/releases/download/OpenWrt-v24.10.2/x86_64.json -O x86_64.json
          wget -q https://github.com/zhiern/ZeroWrt/releases/download/OpenWrt-v24.10.2/rockchip.json -O rockchip.json
          jq -s '.' x86_64.json rockchip.json > ota/ota.json
     
      - name: Release OTA
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.ftp_address }}
          username: ftpopenwrt
          password: ${{ secrets.ftp_password }}
          server-dir: ota/
          local-dir: ota/
          dangerous-clean-slate: true

      - name: Sync kernel modules
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.workflow_token }}
          repository: zhiern/openwrt-core
          event-type: sync

      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        continue-on-error: true
        with:
          token: ${{ secrets.workflow_token }}
          retain_days: 0
          keep_minimum_runs: 0

      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
            keep_latest: 3
            keep_min_download_counts: 1 # Optional parameters
            delete_tags: true
        env:
            GITHUB_TOKEN: ${{ secrets.workflow_token }}
